#!/bin/bash

# clean a single example from a folder in the parent directory
BUILD_DIR="${0%/*}"/../$1/build
if [ -e $BUILD_DIR ]; then
	rm -rf $BUILD_DIR
else
	echo "Nothing to clean for example '$1', skipping..."
fi

